<?php
$steps = [
    1 => ["Station Setup", '<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px">
<div><label style="font-size:12px;font-weight:600">Station Name</label><input name="name" value="<?php echo htmlspecialchars($station->name ?? ""); ?>" class="form-control" placeholder="101.2 The Mix"></div>
<div><label style="font-size:12px;font-weight:600">Website URL</label><input name="website_url" value="<?php echo htmlspecialchars($station->website_url ?? ""); ?>" class="form-control" placeholder="https://1012themix.com"></div>
<div style="grid-column:1/-1"><label style="font-size:12px;font-weight:600">Description</label><textarea name="description" class="form-control" rows="2" placeholder="Today\'s Best Music"><?php echo htmlspecialchars($station->description ?? ""); ?></textarea></div>
<div><label style="font-size:12px;font-weight:600">Genre</label><input name="genre" value="<?php echo htmlspecialchars($station->genre ?? ""); ?>" class="form-control" placeholder="Top 40"></div>
<div><label style="font-size:12px;font-weight:600">Timezone</label><select name="timezone" class="form-control"><option value="UTC">UTC</option><option value="America/New_York">Eastern</option><option value="America/Chicago">Central</option><option value="America/Denver">Mountain</option><option value="America/Los_Angeles">Pacific</option></select></div>
<div><label style="font-size:12px;font-weight:600">Station Logo</label><input type="file" name="logo" accept="image/*" class="form-control" style="padding:6px"></div>
</div>'],
    2 => ["Stream Setup", '<input type="hidden" name="server_type" value="icecast"><div style="margin-top:14px;padding:14px;background:rgba(0,140,255,.06);border:1px solid rgba(0,140,255,.12);border-radius:8px"><p style="font-size:13px">Γ¥ä∩╕Å Server Type: <strong>Icecast</strong></p><p style="color:#64748b;font-size:11px;margin-top:4px">Bitrate and channels are set by your hosting package.</p></div>'],
    3 => ["Upload Music", '<div style="text-align:center;padding:20px"><div style="font-size:48px;margin-bottom:10px">≡ƒÄ╢</div><p style="font-size:13px;font-weight:600">Upload your music library</p><p style="color:#64748b;font-size:11px;margin-bottom:12px">MP3, AAC, OGG, FLAC, WAV</p><a href="/radio?tab=media" class="btn btn-primary">≡ƒÄ╢ Open Media Manager</a></div>'],
    4 => ["Organize Music", '<p style="color:#64748b;font-size:12px">Click folders to toggle.</p><div class="folder-grid" style="margin-top:10px">'.implode("", array_map(function($f){return "<label class=\"folder-tag selected\"><input type=\"checkbox\" name=\"folders[]\" value=\"$f\" checked style=\"display:none\"> $f</label>";}, ["Rock","Country","Hip-Hop","Pop","Oldies","Commercials","Talk Shows","Jazz","Classical","R&B","Electronic","Alternative","Metal","Indie","Latin","Reggae","Blues","Folk","Podcasts","Soundtracks"])).'</div>'],
    5 => ["Build Playlist", '<div style="display:grid;gap:10px;margin-top:14px">'.implode("", array_map(function($r){return "<label style=\"display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.04);font-size:13px\"><input type=\"checkbox\" name=\"playlists[]\" value=\"$r\" checked> $r</label>";}, ["Main Rotation","Night Rotation","Weekend Rotation","Holiday Rotation"])).'</div>'],
    6 => ["AutoDJ Schedule", '<div class="opt-group" style="grid-template-columns:1fr 1fr;margin-top:14px"><label class="opt-card"><input type="radio" name="autodj_schedule" value="24_7"><div style="font-size:12px;font-weight:600">≡ƒöä Run 24/7</div></label><label class="opt-card"><input type="radio" name="autodj_schedule" value="offline_only" checked><div style="font-size:12px;font-weight:600">≡ƒÄñ Only When DJs Offline</div></label></div>'],
    7 => ["DJ Handoff", '<div style="margin-top:14px"><label style="font-size:12px;font-weight:600">When DJ Connects</label><div class="opt-group" style="grid-template-columns:1fr 1fr 1fr"><label class="opt-card"><input type="radio" name="autodj_dj_handoff" value="stop"><div style="font-size:12px;font-weight:600">ΓÅ╣ Stop AutoDJ</div></label><label class="opt-card"><input type="radio" name="autodj_dj_handoff" value="fade_out" checked><div style="font-size:12px;font-weight:600">≡ƒÄÜ Fade Out</div></label><label class="opt-card"><input type="radio" name="autodj_dj_handoff" value="keep"><div style="font-size:12px;font-weight:600">Γû╢∩╕Å Keep Running</div></label></div></div><div style="margin-top:14px;padding-top:14px;border-top:1px solid rgba(255,255,255,.06)"><label style="display:flex;align-items:center;gap:8px;font-size:13px"><input type="checkbox" name="autodj_auto_resume" value="1" checked><strong>Auto-Resume</strong> when DJ disconnects</label></div>'],
    8 => ["Song Requests", '<div class="opt-group" style="grid-template-columns:1fr 1fr;max-width:260px;margin-top:14px"><label class="opt-card"><input type="radio" name="requests_enabled" value="1" checked><div style="font-size:12px;font-weight:600">Γ£à Enable</div></label><label class="opt-card"><input type="radio" name="requests_enabled" value="0"><div style="font-size:12px;font-weight:600">Γ¥î Disable</div></label></div>'],
];
$step = (int)($_GET["step"] ?? 1);
?>
<style>.wizard-step{display:none}.wizard-step.active{display:block}.wizard-nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.wizard-steps{display:flex;gap:6px}.wizard-dot{width:28px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;background:rgba(255,255,255,.06);color:#64748b}.wizard-dot.active{background:rgba(0,140,255,.2);color:#0A84FF}.wizard-dot.done{background:rgba(74,222,128,.15);color:#4ade80}.setup-card{background:rgba(8,16,28,.85);border:1px solid rgba(0,191,255,.08);border-radius:12px;padding:24px;margin-bottom:14px}.setup-card h3{font-size:16px;margin:0 0 4px}.setup-card .step-num{font-size:11px;color:#64748b;margin-bottom:14px}.folder-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:6px}.folder-tag{padding:8px 12px;background:rgba(0,140,255,.06);border:1px solid rgba(0,140,255,.12);border-radius:6px;font-size:12px;text-align:center;cursor:pointer}.folder-tag.selected{background:rgba(0,140,255,.15);border-color:#0A84FF}.opt-group{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:8px;margin:10px 0}.opt-card{border:1px solid rgba(255,255,255,.08);border-radius:8px;padding:12px;text-align:center;cursor:pointer;transition:.15s}.opt-card:hover{border-color:rgba(0,140,255,.3);background:rgba(0,140,255,.04)}.opt-card.selected{border-color:#0A84FF;background:rgba(0,140,255,.1)}.opt-card input{display:none}</style>
<div class="wizard-nav"><div><h2>≡ƒÜÇ AutoDJ Setup Wizard</h2></div><div class="wizard-steps"><?php for($i=1;$i<=8;$i++): ?><div class="wizard-dot <?php echo $i==$step?"active":($i<$step?"done":"");?>"><?php echo $i;?></div><?php endfor; ?></div></div>
<p style="color:#64748b;margin-bottom:20px">Follow the steps to configure your station.</p>
<form method="POST" action="/radio/setup/save-wizard" enctype="multipart/form-data">
<?php foreach($steps as $num=>$info): ?>
<div class="wizard-step <?php echo $step==$num?"active":"";?>">
<div class="setup-card"><div class="step-num">Step <?php echo $num;?> of 8</div><h3><?php echo $info[0];?></h3><?php echo $info[1];?></div>
<?php if($num>1): ?><a href="?step=<?php echo $num-1;?>" class="btn btn-secondary btn-sm">ΓåÉ Back</a> <?php endif; ?>
<?php if($num<8): ?><a href="?step=<?php echo $num+1;?>" class="btn btn-primary">Next ΓåÆ</a><?php else: ?><button type="submit" class="btn btn-success">Γ£à Complete Setup</button><?php endif; ?>
</div>
<?php endforeach; ?>
</form>
<script>document.querySelectorAll(".folder-tag").forEach(function(n){n.addEventListener("click",function(){var c=this.querySelector("input");c.checked=!c.checked;this.classList.toggle("selected")})});</script>
