#!/bin/bash

# =========================================================
# Planet Hosts Master Panel Uninstaller
# Removes only files and data created by this software.
# =========================================================

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PANEL_DIR="/var/www/radiohosting"

clear

echo "=================================================="
echo " Planet Hosts Master Panel Uninstaller"
echo "=================================================="
echo ""
echo "This will remove:"
echo ""
echo " - All panel files"
echo " - Apache virtual host config"
echo " - Panel cron jobs"
echo " - Panel logs"
echo " - Icecast config (if any)"
echo " - The radiohosting database"
echo ""
echo "System packages, firewall rules, and other"
echo "software on this server will NOT be touched."
echo ""

read -p "Continue? (y/N): " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled."
    exit 1
fi

# ---- Stop panel services ----
echo ""
echo "Stopping panel services..."

for service in httpd icecast icecast2; do
    if systemctl list-unit-files 2>/dev/null | grep -q "$service"; then
        systemctl stop "$service" 2>/dev/null || true
    fi
done

# ---- Apache vhost ----
echo "Removing Apache virtual host config..."
rm -f /etc/httpd/conf.d/radiohosting.conf

# Restore welcome.conf if we disabled it
if [ -f /etc/httpd/conf.d/welcome.conf.disabled ]; then
    mv /etc/httpd/conf.d/welcome.conf.disabled /etc/httpd/conf.d/welcome.conf 2>/dev/null || true
fi

# ---- Cron ----
echo "Removing cron jobs..."
rm -f /etc/cron.d/radiohosting

# ---- Panel files ----
echo "Removing panel files..."
rm -rf "$PANEL_DIR"
rm -rf /var/log/radiohosting
rm -rf /tmp/radiohosting_panel 2>/dev/null || true
rm -rf /tmp/whm 2>/dev/null || true

# ---- Icecast config (generated by this panel) ----
echo "Removing Icecast config..."
rm -rf /usr/local/etc/icecast 2>/dev/null || true
rm -rf /usr/local/var/log/icecast 2>/dev/null || true
rm -rf /usr/local/var/run/icecast 2>/dev/null || true
rm -f /etc/systemd/system/icecast.service 2>/dev/null || true

# ---- rc.local entries ----
sed -i '/radiohosting/d' /etc/rc.d/rc.local 2>/dev/null || true

# ---- Database ----
# ---- User radio directories ----
echo ""
echo "Removing user radio files from /home/*/radio/..."
find /home -maxdepth 2 -type d -name radio -exec rm -rf {} + 2>/dev/null || true

echo ""
read -p "Drop the radiohosting database and user? (y/N): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    if mysqladmin -u root ping >/dev/null 2>&1; then
        MYSQL_ROOT_OPTS="-u root"
    else
        read -s -p "MariaDB root password: " MYSQL_ROOT_PASSWORD
        echo
        MYSQL_ROOT_OPTS="-u root -p$MYSQL_ROOT_PASSWORD"
    fi

    mysql $MYSQL_ROOT_OPTS -e "DROP DATABASE IF EXISTS radiohosting;" || true
    mysql $MYSQL_ROOT_OPTS -e "DROP USER IF EXISTS 'radiouser'@'localhost';" || true
    mysql $MYSQL_ROOT_OPTS -e "FLUSH PRIVILEGES;" || true
    echo "Database removed."
fi

# ---- Done ----
echo ""
echo "=================================================="
echo " Uninstallation Complete"
echo "=================================================="
echo ""
echo "All Planet Hosts panel files and data have been"
echo "removed from this server."
echo ""
echo "System packages, firewall rules, and other"
echo "services were left untouched."
echo ""

