<?php
/**
 * Liquidsoap Manager — Seamless AutoDJ ↔ Live DJ source switching
 *
 * Generates per-station Liquidsoap scripts, manages processes.
 * Liquidsoap handles fallback(source1, source2) for instant switching.
 *
 * Requires: Liquidsoap 2.x installed on server
 */

class LiquidsoapManager
{
    protected $pdo;
    protected $liquidsoapBin = '/usr/bin/liquidsoap';
    protected $scriptsDir = '/var/www/radiohosting/config/liquidsoap';
    protected $logDir = '/var/log/liquidsoap';

    public function __construct()
    {
        $this->pdo = new PDO(
            'mysql:host=localhost;dbname=radiohosting;charset=utf8mb4',
            'radiouser',
            'Skylinehosting171',
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        @mkdir($this->scriptsDir, 0755, true);
        @mkdir($this->logDir, 0755, true);
    }

    public function isInstalled()
    {
        $out = trim(shell_exec('which liquidsoap 2>/dev/null') ?: '');
        return !empty($out);
    }

    public function getVersion()
    {
        $out = shell_exec($this->liquidsoapBin . ' --version 2>/dev/null');
        if (preg_match('/Liquidsoap ([\d.]+)/', $out, $m)) return $m[1];
        return null;
    }

    public function isRunning($stationId)
    {
        $pidFile = $this->getPidFile($stationId);
        if (!file_exists($pidFile)) return false;
        $pid = (int)trim(@file_get_contents($pidFile));
        if ($pid <= 0) return false;
        return @posix_kill($pid, 0);
    }

    public function generateConfig($stationId)
    {
        $s = $this->pdo->prepare("SELECT * FROM streaming_stations WHERE id = ?");
        $s->execute([$stationId]);
        $station = $s->fetch(PDO::FETCH_OBJ);
        if (!$station) return false;

        $engine = $station->engine ?? 'icecast';
        $sourcePass = $station->plain_password ?: $station->password ?? 'radio';
        $port = (int)$station->port;
        $mount = $station->mount_point ?? '/stream';
        $bitrate = (int)($station->bitrate ?? 128);
        $format = $station->format ?? 'mp3';
        $name = addslashes($station->name ?? 'Radio Station');
        $host = '127.0.0.1';

        // Internal ports for AutoDJ and live DJ inputs
        $autodjPort = 16000 + $stationId;  // AutoDJ HTTP source
        $liveDjPort = 17000 + $stationId;  // Live DJ harbor input

        // Determine output protocol
        $output = '';
        $encoder = '%mp3(bitrate=' . $bitrate . ')';
        if ($format === 'aac') $encoder = '%fdkaac(bitrate=' . $bitrate . ')';
        elseif ($format === 'ogg' || $format === 'vorbis') $encoder = '%vorbis(bitrate=' . $bitrate . ')';
        elseif ($format === 'opus') $encoder = '%opus(bitrate=' . $bitrate . ')';
        elseif ($format === 'flac') $encoder = '%flac()';

        if ($engine === 'shoutcast' || $engine === 'shoutcast2') {
            $output = "output.shoutcast($encoder, host=\"$host\", port=$port, password=\"$sourcePass\", name=\"$name\", public=true, radio)";
        } else {
            $output = "output.icecast($encoder, host=\"$host\", port=$port, password=\"$sourcePass\", mount=\"$mount\", name=\"$name\", radio)";
        }

        $script = <<<LIQ
# Liquidsoap config for station {$station->id} — {$station->name}
# Auto-generated by Planet Hosts Panel

set("log.file", "{$this->logDir}/station_{$stationId}.log")
set("log.level", 3)
set("server.telnet", false)
set("harbor.bind_addr", "127.0.0.1")

# AutoDJ source (HTTP — fed by ffmpeg or PHP AutoDJ player)
autodj = input.http("http://127.0.0.1:{$autodjPort}/autodj", max=30.)

# Live DJ source (Harbor — fed by DjPortListener relay)
live_dj = input.harbor("live_dj", port={$liveDjPort}, max=30., timeout=20.)

# Seamless fallback: live DJ takes priority, AutoDJ is fallback
radio = fallback(track_sensitive=false, [live_dj, autodj])

# Output to streaming engine
{$output}

LIQ;

        $path = $this->getConfigPath($stationId);
        file_put_contents($path, $script);

        // Store harbor port in station config for DjPortListener to use
        $this->pdo->prepare("UPDATE streaming_stations SET liquidsoap_port=? WHERE id=?")
            ->execute([$liveDjPort, $stationId]);

        return $path;
    }

    public function start($stationId)
    {
        if ($this->isRunning($stationId)) return true;
        $config = $this->generateConfig($stationId);
        if (!$config || !file_exists($config)) return false;

        $pidFile = $this->getPidFile($stationId);
        $logFile = $this->logDir . '/station_' . $stationId . '.log';

        $cmd = "nohup {$this->liquidsoapBin} \"$config\" > \"$logFile\" 2>&1 & echo $!";
        $pid = trim(shell_exec($cmd) ?: '');
        if (!empty($pid) && is_numeric($pid)) {
            file_put_contents($pidFile, $pid);
            return true;
        }
        return false;
    }

    public function stop($stationId)
    {
        $pidFile = $this->getPidFile($stationId);
        if (!file_exists($pidFile)) return true;
        $pid = (int)trim(@file_get_contents($pidFile));
        if ($pid > 0) @posix_kill($pid, 15);
        usleep(300000);
        if ($pid > 0) @posix_kill($pid, 9);
        @unlink($pidFile);
        return true;
    }

    public function restart($stationId)
    {
        $this->stop($stationId);
        sleep(1);
        return $this->start($stationId);
    }

    protected function getConfigPath($stationId)
    {
        return $this->scriptsDir . '/station_' . $stationId . '.liq';
    }

    protected function getPidFile($stationId)
    {
        return $this->scriptsDir . '/station_' . $stationId . '.pid';
    }
}
