CREATE TABLE IF NOT EXISTS webhooks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  url VARCHAR(500) NOT NULL,
  events VARCHAR(255) NOT NULL DEFAULT 'all',
  secret VARCHAR(64) DEFAULT '',
  is_active TINYINT(1) DEFAULT 1,
  last_triggered_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS rate_limit INT DEFAULT 60 AFTER permissions;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS is_active TINYINT(1) DEFAULT 1 AFTER rate_limit;
