-- Planet Hosts bootstrap tables
-- Base tables that many application features and legacy migrations depend on but
-- which were never shipped as a migration. The migration runner executes this file
-- BEFORE any migration so both fresh installs and updates converge on the same schema.
-- All statements are idempotent (CREATE TABLE IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS api_keys (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL DEFAULT 'API Key',
  key_hash VARCHAR(255) NOT NULL,
  permissions VARCHAR(255) NOT NULL DEFAULT 'read',
  rate_limit INT(11) NOT NULL DEFAULT 60,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  user_id INT(11) DEFAULT NULL,
  user_type VARCHAR(20) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_key_hash (key_hash),
  KEY idx_user (user_id, user_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS feature_lists (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  email_accounts INT(11) NOT NULL DEFAULT -1,
  ftp_accounts INT(11) NOT NULL DEFAULT -1,
  databases INT(11) NOT NULL DEFAULT -1,
  database_users INT(11) NOT NULL DEFAULT -1,
  subdomains INT(11) NOT NULL DEFAULT -1,
  parked_domains INT(11) NOT NULL DEFAULT -1,
  addon_domains INT(11) NOT NULL DEFAULT -1,
  cron_jobs INT(11) NOT NULL DEFAULT 0,
  ssh_access TINYINT(1) NOT NULL DEFAULT 0,
  ssl_allowed TINYINT(1) NOT NULL DEFAULT 0,
  git_access TINYINT(1) NOT NULL DEFAULT 0,
  nodejs TINYINT(1) NOT NULL DEFAULT 0,
  python TINYINT(1) NOT NULL DEFAULT 0,
  ruby TINYINT(1) NOT NULL DEFAULT 0,
  terminal TINYINT(1) NOT NULL DEFAULT 0,
  backups TINYINT(1) NOT NULL DEFAULT 0,
  installer TINYINT(1) NOT NULL DEFAULT 0,
  chatbox TINYINT(1) NOT NULL DEFAULT 0,
  chatbox_voice TINYINT(1) NOT NULL DEFAULT 0,
  chatbox_video TINYINT(1) NOT NULL DEFAULT 0,
  game TINYINT(1) NOT NULL DEFAULT 0,
  radio TINYINT(1) NOT NULL DEFAULT 0,
  shoutcast TINYINT(1) NOT NULL DEFAULT 0,
  dj_panel TINYINT(1) NOT NULL DEFAULT 0,
  builder TINYINT(1) NOT NULL DEFAULT 0,
  ai_website_builder TINYINT(1) NOT NULL DEFAULT 0,
  ai_assistant TINYINT(1) NOT NULL DEFAULT 0,
  plugin_marketplace TINYINT(1) NOT NULL DEFAULT 0,
  api_access TINYINT(1) NOT NULL DEFAULT 0,
  webhooks TINYINT(1) NOT NULL DEFAULT 0,
  streaming_enabled TINYINT(1) NOT NULL DEFAULT 0,
  shoutcast_v1 TINYINT(1) NOT NULL DEFAULT 0,
  shoutcast_v2 TINYINT(1) NOT NULL DEFAULT 0,
  icecast_enabled TINYINT(1) NOT NULL DEFAULT 0,
  max_stations INT(11) NOT NULL DEFAULT 0,
  max_djs INT(11) NOT NULL DEFAULT 0,
  max_listeners INT(11) NOT NULL DEFAULT 0,
  max_bitrate INT(11) NOT NULL DEFAULT 0,
  autodj TINYINT(1) NOT NULL DEFAULT 0,
  ssl_streaming TINYINT(1) NOT NULL DEFAULT 0,
  playlist_storage TINYINT(1) NOT NULL DEFAULT 0,
  statistics TINYINT(1) NOT NULL DEFAULT 0,
  recording TINYINT(1) NOT NULL DEFAULT 0,
  song_requests TINYINT(1) NOT NULL DEFAULT 0,
  game_servers_enabled TINYINT(1) NOT NULL DEFAULT 0,
  max_game_servers INT(11) NOT NULL DEFAULT 0,
  steamcmd TINYINT(1) NOT NULL DEFAULT 0,
  workshop TINYINT(1) NOT NULL DEFAULT 0,
  mod_support TINYINT(1) NOT NULL DEFAULT 0,
  scheduled_restarts TINYINT(1) NOT NULL DEFAULT 0,
  automatic_updates TINYINT(1) NOT NULL DEFAULT 0,
  game_backups TINYINT(1) NOT NULL DEFAULT 0,
  vps_enabled TINYINT(1) NOT NULL DEFAULT 0,
  vcpu INT(11) NOT NULL DEFAULT 0,
  ram INT(11) NOT NULL DEFAULT 0,
  vps_storage INT(11) NOT NULL DEFAULT 0,
  vps_bandwidth INT(11) NOT NULL DEFAULT 0,
  snapshots INT(11) NOT NULL DEFAULT 0,
  iso_mount TINYINT(1) NOT NULL DEFAULT 0,
  vps_backups TINYINT(1) NOT NULL DEFAULT 0,
  ipv4 INT(11) NOT NULL DEFAULT 0,
  ipv6 INT(11) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mail_accounts (
  id INT(11) NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  domain VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  password_hash VARCHAR(255) DEFAULT NULL,
  password_plain VARCHAR(255) DEFAULT NULL,
  quota INT(11) DEFAULT 1000,
  quota_mb INT(11) DEFAULT 1000,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_email (email),
  KEY idx_domain (domain)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wb_templates (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) DEFAULT NULL,
  description TEXT,
  thumbnail VARCHAR(255) DEFAULT NULL,
  config JSON DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_visitors (
  id INT(11) NOT NULL AUTO_INCREMENT,
  session_id VARCHAR(255) DEFAULT '',
  ip_address VARCHAR(45) DEFAULT '',
  current_page VARCHAR(500) DEFAULT '',
  timezone VARCHAR(64) DEFAULT '',
  language VARCHAR(16) DEFAULT '',
  browser VARCHAR(64) DEFAULT '',
  os VARCHAR(64) DEFAULT '',
  page_history TEXT,
  time_on_site INT(11) NOT NULL DEFAULT 0,
  first_seen DATETIME DEFAULT NULL,
  last_seen DATETIME DEFAULT NULL,
  name VARCHAR(100) DEFAULT '',
  email VARCHAR(255) DEFAULT '',
  hosting_user_id INT(11) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_session (session_id),
  KEY idx_last_seen (last_seen)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_sessions (
  id INT(11) NOT NULL AUTO_INCREMENT,
  visitor_id INT(11) DEFAULT NULL,
  visitor_name VARCHAR(100) DEFAULT '',
  visitor_email VARCHAR(255) DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'waiting',
  department VARCHAR(100) DEFAULT 'General',
  subject VARCHAR(255) DEFAULT '',
  last_activity DATETIME DEFAULT NULL,
  closed_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_visitor (visitor_id),
  KEY idx_status (status),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;