CREATE TABLE IF NOT EXISTS game_slot_pricing (
    id INT AUTO_INCREMENT PRIMARY KEY,
    game_type_id INT NOT NULL DEFAULT 0,
    min_slots INT NOT NULL DEFAULT 1,
    max_slots INT NOT NULL DEFAULT 100,
    price_per_slot DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS game_packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    game_type_id INT NOT NULL DEFAULT 0,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    slots INT NOT NULL DEFAULT 10,
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    setup_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    billing_cycle VARCHAR(50) NOT NULL DEFAULT 'monthly',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
