-- REQ #6: account contact/payment/avatar profile fields (PIN columns already exist)
ALTER TABLE hosting_users
  ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS city VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS state VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS zip VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS country VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS avatar VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS payment_gateway VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS payment_gateway_id VARCHAR(255) NULL;
