CREATE TABLE IF NOT EXISTS `radio_autodj_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `station_id` int(11) NOT NULL,
  `wizard_completed` tinyint(1) DEFAULT 0,
  `wizard_step` int(11) DEFAULT 0,
  `station_name` varchar(255) DEFAULT NULL,
  `station_description` text DEFAULT NULL,
  `genre` varchar(100) DEFAULT NULL,
  `language` varchar(50) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `timezone` varchar(50) DEFAULT 'UTC',
  `station_website` varchar(255) DEFAULT NULL,
  `station_email` varchar(255) DEFAULT NULL,
  `streaming_engine` varchar(20) DEFAULT 'icecast',
  `audio_codec` varchar(10) DEFAULT 'mp3',
  `bitrate` int(11) DEFAULT 128,
  `sample_rate` int(11) DEFAULT 44100,
  `channels` varchar(10) DEFAULT 'stereo',
  `autodj_enabled` tinyint(1) DEFAULT 0,
  `playlist_mode` varchar(20) DEFAULT 'sequential',
  `crossfade_enabled` tinyint(1) DEFAULT 1,
  `crossfade_time` int(11) DEFAULT 5,
  `normalize_audio` tinyint(1) DEFAULT 1,
  `replaygain` tinyint(1) DEFAULT 1,
  `silence_detection` tinyint(1) DEFAULT 1,
  `remove_duplicates` tinyint(1) DEFAULT 1,
  `max_artist_repeat` int(11) DEFAULT 60,
  `max_song_repeat` int(11) DEFAULT 240,
  `max_album_repeat` int(11) DEFAULT 120,
  `shuffle_enabled` tinyint(1) DEFAULT 1,
  `weight_new_songs` tinyint(1) DEFAULT 1,
  `weight_favorites` tinyint(1) DEFAULT 1,
  `allow_live_djs` tinyint(1) DEFAULT 1,
  `auto_switch_dj` tinyint(1) DEFAULT 1,
  `fallback_autodj` tinyint(1) DEFAULT 1,
  `reconnect_time` int(11) DEFAULT 30,
  `jingles_enabled` tinyint(1) DEFAULT 0,
  `jingle_play_every` int(11) DEFAULT 15,
  `jingle_position` varchar(20) DEFAULT 'random',
  `ads_enabled` tinyint(1) DEFAULT 0,
  `max_ads_per_hour` int(11) DEFAULT 4,
  `requests_enabled` tinyint(1) DEFAULT 1,
  `request_delay` int(11) DEFAULT 30,
  `max_requests_per_listener` int(11) DEFAULT 2,
  `metadata_update` tinyint(1) DEFAULT 1,
  `backup_frequency` varchar(10) DEFAULT 'daily',
  `cloud_backup` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `station_id` (`station_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `radio_autodj_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `station_id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'music',
  `playlist_id` int(11) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `station_id` (`station_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `radio_autodj_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `station_id` int(11) NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'info',
  `message` text NOT NULL,
  `details` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `station_id` (`station_id`),
  KEY `type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `radio_autodj_ai_memory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `station_id` int(11) NOT NULL,
  `query` text NOT NULL,
  `response` text NOT NULL,
  `applied` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `station_id` (`station_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
