-- Seed default templates
INSERT IGNORE INTO wb_templates (name, description, config) VALUES
('Business Pro', 'Professional business website with hero, services, team, contact sections', '{"category":"business","pages":[{"name":"Home","sections":["hero","services","about","team","contact"]},{"name":"About","sections":["about","team"]},{"name":"Services","sections":["services","pricing"]},{"name":"Contact","sections":["contact","map"]}],"menus":[{"name":"Main","items":[{"label":"Home","link":"/"},{"label":"About","link":"/about"},{"label":"Services","link":"/services"},{"label":"Contact","link":"/contact"}]}]}'),
('Portfolio', 'Creative portfolio for designers, photographers, and artists', '{"category":"portfolio","pages":[{"name":"Home","sections":["hero","gallery","about","testimonials","contact"]},{"name":"Gallery","sections":["gallery","filter"]},{"name":"About","sections":["about","timeline"]}],"menus":[{"name":"Main","items":[{"label":"Home","link":"/"},{"label":"Gallery","link":"/gallery"},{"label":"About","link":"/about"}]}]}'),
('Restaurant', 'Restaurant website with menu, reservations, and location', '{"category":"food","pages":[{"name":"Home","sections":["hero","menu","about","reservations","contact"]},{"name":"Menu","sections":["menu","specials"]},{"name":"Reservations","sections":["reservations"]}],"menus":[{"name":"Main","items":[{"label":"Home","link":"/"},{"label":"Menu","link":"/menu"},{"label":"Reservations","link":"/reservations"}]}]}'),
('Blog', 'Modern blog with articles, categories, and sidebar', '{"category":"blog","pages":[{"name":"Home","sections":["hero","blog","featured"]},{"name":"Blog","sections":["blog","sidebar"]},{"name":"About","sections":["about"]}],"menus":[{"name":"Main","items":[{"label":"Home","link":"/"},{"label":"Blog","link":"/blog"},{"label":"About","link":"/about"}]}]}'),
('Landing Page', 'High-converting landing page for products and services', '{"category":"marketing","pages":[{"name":"Home","sections":["hero","features","benefits","testimonials","cta","pricing","contact"]}],"menus":[]}'),
('E-Commerce', 'Online store with product listings, cart, and checkout', '{"category":"ecommerce","pages":[{"name":"Home","sections":["hero","products","featured","categories"]},{"name":"Shop","sections":["products","filter"]},{"name":"Cart","sections":["cart"]},{"name":"Checkout","sections":["checkout"]}],"menus":[{"name":"Main","items":[{"label":"Home","link":"/"},{"label":"Shop","link":"/shop"},{"label":"Cart","link":"/cart"}]}]}');

-- Seed default themes
INSERT IGNORE INTO wb_themes (name, css, config) VALUES
('Dark Modern', '/* Dark Modern theme */ body{background:#02050e;color:#e0e0e0} a{color:#008cff}', '{"version":"1.0","description":"Sleek dark theme with blue accents","author":"Planet Hosts","primary":"#008cff","secondary":"#00e5ff","bg":"#02050e","card_bg":"rgba(8,16,28,.85)","text":"#ffffff","accent":"#38bdf8"}'),
('Light Clean', '/* Light Clean theme */ body{background:#ffffff;color:#1e293b} a{color:#2563eb}', '{"version":"1.0","description":"Clean light theme","author":"Planet Hosts","primary":"#2563eb","secondary":"#7c3aed","bg":"#ffffff","card_bg":"#f8fafc","text":"#1e293b","accent":"#3b82f6"}'),
('Nature', '/* Nature theme */ body{background:#f0fdf4;color:#166534} a{color:#059669}', '{"version":"1.0","description":"Earthy green theme","author":"Planet Hosts","primary":"#059669","secondary":"#34d399","bg":"#f0fdf4","card_bg":"#ffffff","text":"#166534","accent":"#10b981"}'),
('Midnight', '/* Midnight theme */ body{background:#0f0a1a;color:#e0e0e0} a{color:#7c3aed}', '{"version":"1.0","description":"Deep purple-dark theme","author":"Planet Hosts","primary":"#7c3aed","secondary":"#a78bfa","bg":"#0f0a1a","card_bg":"rgba(15,10,26,.9)","text":"#e0e0e0","accent":"#8b5cf6"}'),
('Corporate', '/* Corporate theme */ body{background:#f0f4ff;color:#1e293b} a{color:#1e40af}', '{"version":"1.0","description":"Professional blue theme","author":"Planet Hosts","primary":"#1e40af","secondary":"#3b82f6","bg":"#f0f4ff","card_bg":"#ffffff","text":"#1e293b","accent":"#2563eb"}');
