ALTER TABLE radio_djs ADD COLUMN IF NOT EXISTS profile_data TEXT DEFAULT NULL AFTER avatar;
ALTER TABLE radio_djs ADD COLUMN IF NOT EXISTS gallery TEXT DEFAULT NULL AFTER profile_data;
SELECT 'PROFILE_COLS_OK' AS result;
