<?php

namespace Plugins\Radio\Services;

class ShoutcastV1Driver implements StreamingDriverInterface
{
    protected $db;
    protected $installDir = '/opt/planethosts/shoutcast1';
    protected $binaryName = 'sc_serv';

    public function __construct($db) { $this->db = $db; }

    public function getDisplayName() { return 'SHOUTcast v1'; }
    public function getBinaryPath() { return "{$this->installDir}/{$this->binaryName}"; }
    public function getVersion() { return file_exists($this->getBinaryPath()) ? '1.x' : 'not installed'; }
    public function isInstalled() { return file_exists($this->getBinaryPath()); }
    public function isRunning() { return !empty(trim(shell_exec("pgrep -x sc_serv 2>/dev/null") ?: '')) && file_exists($this->getBinaryPath()); }

    public function install($installPath = null)
    {
        $src = $installPath ?: dirname(dirname(dirname(__DIR__))) . '/public';
        $bin = "{$src}/sc_serv";
        if (!file_exists($bin)) return ['success' => false, 'output' => 'sc_serv v1 binary not found at ' . $bin];

        if (!is_dir($this->installDir)) mkdir($this->installDir, 0755, true);
        copy($bin, $this->getBinaryPath());
        chmod($this->getBinaryPath(), 0755);
        foreach (['logs','control'] as $d) { $p = "{$this->installDir}/{$d}"; if (!is_dir($p)) mkdir($p, 0755, true); }
        return ['success' => true, 'output' => "SHOUTcast v1 installed to {$this->installDir}"];
    }

    public function uninstall()
    {
        $this->stopAllV1Stations();
        if (is_dir($this->installDir)) shell_exec("rm -rf " . escapeshellarg($this->installDir));
    }

    public function createStation($userId, $data = [])
    {
        if (!$this->isInstalled()) throw new \Exception('SHOUTcast v1 not installed');
        $port = $data['port'] ?? $this->allocatePort();
        $password = $data['password'] ?? bin2hex(random_bytes(8));
        $name = $data['name'] ?? 'My V1 Station';
        $bitrate = $data['bitrate'] ?? 128;
        $maxListeners = $data['max_listeners'] ?? 100;
        $public = $data['public_server'] ?? 0;
        $format = $data['format'] ?? 'mp3';
        $username = $this->getUsername($userId);

        $stationDir = "/home/{$username}/v1stations/{$port}/";
        foreach (['logs','ssl','playlists','autodj','metadata','backups','tmp'] as $d) @mkdir("{$stationDir}{$d}", 0755, true);

        $configPath = "{$stationDir}sc_serv.conf";
        $config = "; SHOUTcast v1 Configuration\n; Generated by Planet Hosts\n; Port: {$port}\n\n"
            . "LogFile={$stationDir}logs/sc_serv.log\n"
            . "ScreenLog=0\n"
            . "W3CEnabled=0\n"
            . "W3CLog={$stationDir}logs/sc_w3c.log\n"
            . "BanFile={$stationDir}sc_serv.ban\n"
            . "RipFile={$stationDir}sc_serv.rip\n"
            . "PortBase={$port}\n"
            . "Password={$password}\n"
            . "MaxUser={$maxListeners}\n"
            . "Bitrate={$bitrate}\n"
            . "Name={$name}\n"
            . "ContentType=" . (['mp3'=>'mp3','aac'=>'aac','ogg'=>'ogg'][$format] ?? 'mp3') . "\n";
        if ($public) $config .= "PublicServer=Always\n";
        file_put_contents($configPath, $config);

        $serviceName = "ph-v1-stream-{$port}";
        $svc = "[Unit]\nDescription=Planet Hosts SHOUTcast V1 Stream (Port {$port})\nAfter=network.target\n\n"
            . "[Service]\nType=simple\nUser={$username}\nExecStart={$this->getBinaryPath()} {$configPath}\n"
            . "ExecStop=/bin/kill -s TERM \$MAINPID\nRestart=on-failure\nRestartSec=10\n\n"
            . "[Install]\nWantedBy=multi-user.target\n";
        file_put_contents("/etc/systemd/system/{$serviceName}.service", $svc);
        shell_exec('systemctl daemon-reload 2>/dev/null');

        $id = $this->db->table('streaming_stations')->insertGetId([
            'user_id' => $userId, 'engine' => 'shoutcast1', 'name' => $name,
            'server_type' => 'shoutcast1', 'port' => $port,
            'password' => password_hash($password, PASSWORD_DEFAULT),
            'mount_point' => '/stream', 'bitrate' => $bitrate, 'format' => $format,
            'max_listeners' => $maxListeners, 'public_server' => $public,
            'config_path' => $configPath, 'systemd_service' => $serviceName, 'status' => 'stopped',
        ]);
        return ['id' => $id, 'port' => $port, 'password' => $password, 'config_path' => $configPath, 'systemd_service' => $serviceName];
    }

    public function deleteStation($station)
    {
        $this->stopStation($station);
        if ($station->systemd_service) {
            shell_exec("systemctl disable {$station->systemd_service}.service 2>/dev/null");
            @unlink("/etc/systemd/system/{$station->systemd_service}.service");
            shell_exec('systemctl daemon-reload 2>/dev/null');
        }
        $stationDir = dirname($station->config_path);
        if (is_dir($stationDir)) shell_exec("rm -rf " . escapeshellarg($stationDir));
        $this->db->table('streaming_stations')->where('id', $station->id)->delete();
    }

    public function startStation($station)
    {
        if (!$station->config_path || !file_exists($station->config_path))
            return ['success' => false, 'error' => 'Config not found'];
        if ($station->systemd_service) shell_exec("systemctl start {$station->systemd_service}.service 2>/dev/null");
        sleep(1);
        $this->db->table('streaming_stations')->where('id', $station->id)->update(['status' => 'running', 'last_started' => date('Y-m-d H:i:s')]);
        return ['success' => true];
    }

    public function stopStation($station)
    {
        if ($station->systemd_service) shell_exec("systemctl stop {$station->systemd_service}.service 2>/dev/null");
        $this->db->table('streaming_stations')->where('id', $station->id)->update(['status' => 'stopped', 'last_stopped' => date('Y-m-d H:i:s')]);
        return ['success' => true];
    }

    public function generateConfig($station)
    {
        $config = "; SHOUTcast v1 Configuration\n; Auto-generated\n; Port: {$station->port}\n\n"
            . "LogFile=" . dirname($station->config_path) . "/logs/sc_serv.log\n"
            . "PortBase={$station->port}\n"
            . "MaxUser={$station->max_listeners}\n"
            . "Bitrate={$station->bitrate}\n"
            . "Name={$station->name}\n";
        file_put_contents($station->config_path, $config);
        return $station->config_path;
    }

    public function getStats($station)
    {
        $xml = @file_get_contents("http://127.0.0.1:{$station->port}/admin.cgi?sid=1", false, stream_context_create(['http' => ['timeout' => 3]]));
        $stats = ['listeners'=>0,'listener_peak'=>0,'bitrate'=>$station->bitrate,'server_name'=>$station->name];
        if ($xml) {
            preg_match('/<CURRENTLISTENERS>(\d+)<\/CURRENTLISTENERS>/', $xml, $m); $stats['listeners'] = (int)($m[1] ?? 0);
            preg_match('/<PEAKLISTENERS>(\d+)<\/PEAKLISTENERS>/', $xml, $m); $stats['listener_peak'] = (int)($m[1] ?? 0);
            preg_match('/<BITRATE>(\d+)<\/BITRATE>/', $xml, $m); $stats['bitrate'] = (int)($m[1] ?? $station->bitrate);
        }
        return $stats;
    }

    public function getLogs($station, $lines = 100)
    {
        $logFile = dirname($station->config_path) . '/logs/sc_serv.log';
        if (!file_exists($logFile)) return [];
        return explode("\n", trim(shell_exec("tail -{$lines} " . escapeshellarg($logFile) . ' 2>/dev/null') ?: ''));
    }

    public function healthCheck($station)
    {
        $portOpen = @fsockopen('127.0.0.1', $station->port, $e, $e, 2);
        $svc = $station->systemd_service ? trim(shell_exec("systemctl is-active {$station->systemd_service}.service 2>/dev/null") ?: '') : '';
        return ['running' => $svc === 'active', 'port_open' => $portOpen !== false, 'listeners' => $this->getStats($station)['listeners'], 'config_exists' => $station->config_path && file_exists($station->config_path), 'binary_exists' => $this->isInstalled()];
    }

    protected function stopAllV1Stations()
    {
        $stations = $this->db->table('streaming_stations')->where('engine', 'shoutcast1')->get() ?: [];
        foreach ($stations as $s) { $this->stopStation($s); }
    }

    protected function allocatePort()
    {
        $used = $this->db->table('streaming_stations')->select('port')->get() ?: [];
        $usedPorts = array_map(fn($s) => $s->port, $used);
        for ($port = 11000; $port <= 12000; $port++) {
            if (!in_array($port, $usedPorts) && !@fsockopen('127.0.0.1', $port, $e, $e, 1)) return $port;
        }
        throw new \Exception('No available ports for SHOUTcast v1');
    }

    protected function getUsername($userId)
    {
        $user = $this->db->table('hosting_users')->where('id', $userId)->first();
        return $user->username ?? "user{$userId}";
    }
}
